variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  SERVICE_NAME: "mod-tile"
  IMAGE_NAME: "docker.ugolok.net/$SERVICE_NAME"
  FULL_IMAGE_NAME: "docker.ugolok.net/$SERVICE_NAME:$CI_COMMIT_TAG"
  BUILD_VERSION: "$CI_COMMIT_SHA"

services:
  - docker:19.03.0-dind

stages:
  - dockerize
  - deploy-staging

build_docker:
  stage: dockerize
  image: docker:19.03.0
  allow_failure: false
  script:
    - docker login -u $CI_DOCKER_LOGIN -p $CI_DOCKER_PASSWORD docker.ugolok.net
    - docker build --build-arg DB_PASSWORD --no-cache --force-rm -t $FULL_IMAGE_NAME -t $IMAGE_NAME:latest .
    - docker push $IMAGE_NAME:latest
    - docker push $FULL_IMAGE_NAME
    - docker logout docker.ugolok.net
  only:
    - tags

deploy-staging:
  stage: deploy-staging
  dependencies:
    - build_docker
  image: dtzar/helm-kubectl
  script:
    - export KUBECONFIG=$K8S_CONFIG_STAGING
    - kubectl config use-context kubernetes-admin@ugolok --user=kubernetes-admin
    - apk add gettext
    - envsubst < ./app.yaml | kubectl apply -f -
    - kubectl rollout status deployment.v1.apps/$SERVICE_NAME
  only:
    - tags
  when: manual