version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    networks:
      - kafka
    healthcheck:
      test: ["CMD", "echo ruok | nc -w 2 -q 2 localhost 2181 | grep imok"]
#      test: ["CMD", "nc", "-vz", "localhost", "2181"]
      interval: 1s
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports: 
      - 9092:9092
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "com.ugolok.notifications:1:1"
      # KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
      # KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
      # KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      # KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      # KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
      # KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    # - ./kafka/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
    networks:
      - kafka
    healthcheck:
      test: ["CMD", "zookeeper-shell.sh zookeeper:2181 <<< \"ls /brokers/ids\" | tail -1 | jq '.[]' | grep 1001"]
#      test: ["CMD", "echo ruok | nc -w 2 -q 2 zookeeper 2181 | grep imok"]
#      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      interval: 1s

networks:
  kafka:
    driver: bridge