version: '3.3'
services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - 5432:5432
    networks:
      - postgres
    environment:
      POSTGRES_DB: ugolok
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "5432"]
      interval: 1s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - 5555:80
    networks:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: secret
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "80"]
      interval: 1s

networks:
  postgres:
    driver: bridge