version: '3.3'
services:
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports: 
      - 9092:9092
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEPER_CONNECT: zookeeper:2181
    healthcheck:
      test: ["CMD", "nc", "-vz", "localhost", "9092"]
      interval: 1s
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    healthcheck:
      test: "echo stat | nc localhost 2181"
      interval: 1s
